#!/usr/bin/env python3
"""Fetch upcoming events from the MoCo Code & Coffee Meetup RSS feed
and write them to _data/events.yml for Jekyll to render statically."""

import re
import sys
import urllib.request
import xml.etree.ElementTree as ET

FEED_URL = 'https://www.meetup.com/mocode-coffee/events/rss/'
OUTPUT   = '_data/events.yml'
MAX_DESC = 150

MONTHS_LONG  = ['January','February','March','April','May','June',
                'July','August','September','October','November','December']
MONTHS_SHORT = ['Jan','Feb','Mar','Apr','May','Jun',
                'Jul','Aug','Sep','Oct','Nov','Dec']


def strip_html(text):
    return re.sub(r'<[^>]+>', '', text or '').strip()


def month_from_title(title):
    """Extract abbreviated month name from an event title like 'MoCo Code & Coffee April'."""
    for i, name in enumerate(MONTHS_LONG):
        if name in (title or ''):
            return MONTHS_SHORT[i]
    return None


def yaml_str(s):
    """Wrap a string in double quotes, escaping backslashes and double quotes."""
    return '"' + s.replace('\\', '\\\\').replace('"', '\\"') + '"'


def fetch_events():
    req = urllib.request.Request(FEED_URL, headers={'User-Agent': 'Mozilla/5.0'})
    with urllib.request.urlopen(req, timeout=10) as resp:
        raw = resp.read().decode('utf-8')

    # Strip namespace prefixes so ElementTree can parse without registering them
    raw = re.sub(r' xmlns(?::\w+)?="[^"]*"', '', raw)
    raw = re.sub(r'<(\w+:)', '<', raw)
    raw = re.sub(r'</(\w+:)', '</', raw)

    root    = ET.fromstring(raw)
    channel = root.find('channel')
    if channel is None:
        return []

    events = []
    for item in channel.findall('item'):
        title = (item.findtext('title') or '').strip()
        url   = (item.findtext('link')  or '').strip()
        desc  = strip_html(item.findtext('description') or '')
        desc  = re.sub(r'\s+', ' ', desc).strip()
        if len(desc) > MAX_DESC:
            desc = desc[:MAX_DESC].rsplit(' ', 1)[0] + '\u2026'

        event = {'title': title, 'url': url, 'description': desc}
        month = month_from_title(title)
        if month:
            event['month'] = month

        events.append(event)

    return events


def write_yaml(events):
    lines = ['# Auto-generated by .github/workflows/fetch-events.yml — do not edit manually\n']
    if not events:
        lines.append('[]\n')
    else:
        for ev in events:
            lines.append('- title: '       + yaml_str(ev['title'])       + '\n')
            lines.append('  url: '         + ev['url']                   + '\n')
            if ev.get('month'):
                lines.append('  month: '   + ev['month']                 + '\n')
            if ev.get('description'):
                lines.append('  description: ' + yaml_str(ev['description']) + '\n')

    with open(OUTPUT, 'w', encoding='utf-8') as f:
        f.writelines(lines)


if __name__ == '__main__':
    try:
        events = fetch_events()
        write_yaml(events)
        print(f'Wrote {len(events)} event(s) to {OUTPUT}')
    except Exception as exc:
        print(f'Error fetching events: {exc}', file=sys.stderr)
        sys.exit(1)
